spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:15433/tscdb_dev
    username: tscdbdev
    password: ericsson
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: none
        